import type { WrappedStats } from "@/types";

/**
 * Export stats as JSON file
 */
export function exportToJSON(stats: WrappedStats): void {
  const json = JSON.stringify(stats, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  downloadBlob(blob, `ado-wrapped-${stats.meta.year}.json`);
}

/**
 * Export stats as Markdown file
 */
export function exportToMarkdown(stats: WrappedStats): void {
  const markdown = generateMarkdown(stats);
  const blob = new Blob([markdown], { type: "text/markdown" });
  downloadBlob(blob, `ado-wrapped-${stats.meta.year}.md`);
}

/**
 * Generate Markdown content from stats
 */
function generateMarkdown(stats: WrappedStats): string {
  const { meta, commits, pullRequests, insights } = stats;

  return `# Azure DevOps Wrapped ${meta.year}

## 📊 Overview

- **Organization:** ${meta.organization}
- **Project:** ${meta.project}
- **Repository:** ${meta.repository}
${meta.userEmail ? `- **User:** ${meta.userEmail}` : ""}
- **Generated:** ${new Date(meta.generatedAt).toLocaleDateString()}

---

## 💻 Commits

- **Total Commits:** ${commits.total.toLocaleString()}
- **Lines Added:** ${commits.additions.toLocaleString()}
- **Lines Modified:** ${commits.edits.toLocaleString()}
- **Lines Deleted:** ${commits.deletions.toLocaleString()}
- **Longest Streak:** ${commits.longestStreak} days 🔥
${
  commits.firstCommitDate
    ? `- **First Commit:** ${new Date(
        commits.firstCommitDate
      ).toLocaleDateString()}`
    : ""
}
${
  commits.lastCommitDate
    ? `- **Last Commit:** ${new Date(
        commits.lastCommitDate
      ).toLocaleDateString()}`
    : ""
}

### Commits by Month

${Object.entries(commits.byMonth || {})
  .sort(([a], [b]) => parseInt(a) - parseInt(b))
  .map(([month, count]) => `- Month ${month}: ${count}`)
  .join("\n")}

### Commits by Day of Week

${Object.entries(commits.byDayOfWeek || {})
  .map(([day, count]) => `- ${day}: ${count}`)
  .join("\n")}

### Commits by Hour

${Object.entries(commits.byHour || {})
  .sort(([a], [b]) => parseInt(a) - parseInt(b))
  .map(([hour, count]) => `- ${hour}:00 - ${count} commits`)
  .join("\n")}

---

## 🔀 Pull Requests

- **Created:** ${pullRequests.created}
- **Merged:** ${pullRequests.merged}
- **Abandoned:** ${pullRequests.abandoned || 0}
- **Reviewed:** ${pullRequests.reviewed}
${
  pullRequests.avgDaysToMergeFormatted
    ? `- **Avg Time to Merge:** ${pullRequests.avgDaysToMergeFormatted}`
    : ""
}
${
  pullRequests.firstPRDate
    ? `- **First PR:** ${new Date(
        pullRequests.firstPRDate
      ).toLocaleDateString()}`
    : ""
}
${
  pullRequests.lastPRDate
    ? `- **Last PR:** ${new Date(pullRequests.lastPRDate).toLocaleDateString()}`
    : ""
}

${
  pullRequests.fastestMerge
    ? `### ⚡ Fastest Merge
- **Title:** ${pullRequests.fastestMerge.title}
- **Time:** ${
        pullRequests.fastestMerge.hours < 24
          ? `${Math.round(pullRequests.fastestMerge.hours)} hours`
          : `${
              Math.round((pullRequests.fastestMerge.hours / 24) * 10) / 10
            } days`
      }
`
    : ""
}

${
  pullRequests.slowestMerge
    ? `### 🐢 Longest Review
- **Title:** ${pullRequests.slowestMerge.title}
- **Time:** ${pullRequests.slowestMerge.days} days
`
    : ""
}

### PRs by Month

${Object.entries(pullRequests.byMonth || {})
  .filter(([, count]) => count > 0)
  .map(([month, count]) => `- ${month}: ${count}`)
  .join("\n")}

### PRs by Day of Week

${Object.entries(pullRequests.byDayOfWeek || {})
  .filter(([, count]) => count > 0)
  .map(([day, count]) => `- ${day}: ${count}`)
  .join("\n")}

${
  pullRequests.largestPR
    ? `
### 🏆 Largest PR

- **Title:** ${pullRequests.largestPR.title}
- **Files Changed:** ${pullRequests.largestPR.filesChanged}
`
    : ""
}

---

${
  insights
    ? `## 🌟 Insights

- **Your Code Personality:** ${insights.personality} ${getPersonalityEmoji(
        insights.personality
      )}
- **Busiest Month:** ${insights.busiestMonth}
- **Busiest Day:** ${insights.busiestDay}
- **Favorite Coding Hour:** ${insights.favoriteCommitHour}:00

### Top File Extensions

${insights.topFileExtensions
  ?.slice(0, 5)
  .map((ext, idx) => `${idx + 1}. \`${ext.ext}\` - ${ext.count} changes`)
  .join("\n")}

---
`
    : ""
}

## 🎉 Summary

${
  commits.total > 100
    ? `You made **${commits.total} commits** this year - that's incredible dedication! `
    : ""
}
${
  pullRequests.merged > 50
    ? `You merged **${pullRequests.merged} pull requests** and collaborated with your team. `
    : ""
}
${
  commits.longestStreak > 7
    ? `Your longest streak of **${commits.longestStreak} days** shows amazing consistency! `
    : ""
}

Keep up the great work! 🚀

---

*Generated by ADO Wrapped - Your Year in Code*
`;
}

/**
 * Get emoji for personality type
 */
function getPersonalityEmoji(personality: string): string {
  const map: Record<string, string> = {
    "Night Owl": "🦉",
    "Early Bird": "🐦",
    "Nine-to-Fiver": "⏰",
    "Weekend Warrior": "⚔️",
  };
  return map[personality] || "💻";
}

/**
 * Download a blob as a file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
